server:
  mode: debug # debug 或者 release
  port: 8081
mysql:
  host: 127.0.0.1
  # host: host.docker.internal
  port: 3306
  database: myblog
  username: root
  password: czl1121741X
#  password: student
  charset: utf8
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
